### PR TITLE
Temporarily remove the execution state field from ODB query

### PR DESCRIPTION
**Pull request by dngomez**
ODB execution state is breaking the UI,

I temporarily removed this field from the query, also removed the UI filter based on this parameter.

### CODE REVIEW

**Review by hugo-vrijswijk — CHANGES_REQUESTED** [review]
I think you are missing a `pnpm install` before running codegen, but otherwise LGTM

**Comment by dngomez** [comment]
How did you notice that, I mean, I didn't change the package-lock.json file, so I don't know what files are being affected if "pnpm install" is not run.

**Comment by hugo-vrijswijk** [comment]
> How did you notice that, I mean, I didn't change the package-lock.json file, so I don't know what files are being affected if "pnpm install" is not run.

I noticed because the codegen diff removes some changes that were added in a recent version (the "Learn more about it here:" text)

**Comment by dngomez** [comment]
Excellent, thank you very much!
I have run the `pnp install` then codegen for the last version.

**Pull request merged**
